services:
  postgres:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_DB: app-database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres

  app:
    build: .
    container_name: application-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata: